"""empty message

Revision ID: 5043a86cad62
Revises: 96ee42311c51
Create Date: 2020-10-17 09:53:28.042337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5043a86cad62'
down_revision = '96ee42311c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'genres', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genres', type_='unique')
    # ### end Alembic commands ###
