"""empty message

Revision ID: 6c0155a36d41
Revises: 92b078f80fbe
Create Date: 2020-10-16 21:54:26.818994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0155a36d41'
down_revision = '92b078f80fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('albums', 'songs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('songs', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_table('songs')
    # ### end Alembic commands ###
